// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFile() {
  return window['go']['main']['App']['ReadFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}
