// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetStartupPaths() {
  return window['go']['main']['App']['GetStartupPaths']();
}

export function GetUserHome() {
  return window['go']['main']['App']['GetUserHome']();
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function ReadFileAt(arg1) {
  return window['go']['main']['App']['ReadFileAt'](arg1);
}

export function SaveFileAt(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAt'](arg1, arg2);
}
