// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath():Promise<string>;

export function OpenFile():Promise<string>;

export function ReadFile():Promise<string>;

export function SaveFile(arg1:string):Promise<void>;
