// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPDF(arg1:string,arg2:string):Promise<void>;

export function GetFileStats(arg1:string):Promise<main.FileStats>;

export function GetStartupPaths():Promise<Array<string>>;

export function GetUserHome():Promise<string>;

export function OpenFilesDialog():Promise<Array<string>>;

export function ReadFileAt(arg1:string):Promise<string>;

export function SaveFileAt(arg1:string,arg2:string):Promise<void>;

export function SaveHTMLDialog(arg1:string):Promise<string>;

export function SaveMarkdownDialog(arg1:string):Promise<string>;

export function SavePDFDialog(arg1:string):Promise<string>;

export function UnwatchFile(arg1:string):Promise<void>;

export function WatchFile(arg1:string):Promise<void>;
